### PR TITLE
Support quasiquotes in types

### PR DESCRIPTION
**Pull request by aavogt**

### CODE REVIEW

**Comment by begriffs** [comment]
Any concerns about merging this? It would be very useful for linting code which uses the `record` library.

**Comment by ndmitchell** [comment]
An HLint user (@magthe) just stumbled across this issue as part of https://github.com/ndmitchell/hlint/issues/133. Merging it and making a release would indeed be quite useful.

**Comment by ndmitchell** [comment]
Reviewing this patch (as an interested bystander, rather than as a maintainer) I see that it adds quasi-quotes as I'd expect, and adds tests as I'd expect, plus dumps a lot of modules in src/Language/Haskell/Meta.hs. These seem to be copyright someone else and not mentioned in the `.cabal` file. Are these accidental inclusions? Perhaps copied from another project? Or are they used in some way? If they are important, I suggest a note justifying them.

**Comment by aavogt** [comment]
It's a mistake to include those Haskell-src-meta modules

**Comment by pjonsson** [comment]
The pretty printing and exact printing looks strange. `TyQuasiQuote.hs.exactprinter.golden` should contain `Match` but there's a dollar sign missing. The same problem seems to happen with the pretty printing.

**Comment by pjonsson** [comment]
Is this something you'd like to have in 1.17 @aavogt?

I had a brief look at the code just in case so we don't get stalled on this. The code looks clean beyond the extra stuff you included by mistake. The two issues I find when looking at the patch:

Both printers seem to drop the `$` that is there in the test input.

The ExactPrint test fails and the code in ExactPrint.hs looks fishy. The code should use `printStringAt`  on the source locations in the AST or `exactPC` on the members the constructor carries. I realize the other code for quasiquotes is equally wrong but that is outside the scope of this issue. I assume the test would pass if this was fixed.

**Comment by expipiplus1** [comment]
It seems as though this has been forgotten. Would it be possible to take another look at this?

**Comment by mpickering** [comment]
Still waiting for @aavogt to reply I think.

**Comment by aavogt** [comment]
this patch addresses merge conflicts, and the extra files included by mistake. But the issues with ExactPrint.hs @pjonsson mentioned are not addressed.

**Comment by mpickering** [comment]
@aavogt I will merge this and sort out the exact printing issue but it seems like you haven't updated the diff?

**Comment by aavogt** [comment]
@mpickering sorry I put those changes on the wrong branch. It looks fixed now

**Comment by mpickering** [comment]
Thanks Adam, I will short this out now.

**Comment by mpickering** [comment]
The `[$qq` quasiquoter syntax has been deprecated since 2010 so I will just change the test to not use it. We don't deal with it properly in normal quasiquoters either.

**Comment by mpickering** [comment]
@pjonsson The exactprinting is fine as the internal representation is strings which include the trailing and leading whitespace.

**Comment by ndmitchell** [comment]
Are you sure this got fixed?

    {-# LANGUAGE QuasiQuotes #-}
    type T = [r| { foo :: Int, bar :: Bool } |]

Gives:

    ParseFailed (SrcLoc "Sample.hs" 2 10) "Parse error: [$r| { foo :: Int, bar :: Bo
ol } ]"

**Pull request closed without merging**
