### PR TITLE
Comments linking (Fixes #213, replaces PR #225)

### LINKED ISSUE #213: Support Haddock comments and linking them back to whatever they apply to
Hello, I would like to have the possibility for haskell-src-exts to link Haddock comments to the construct they apply to. I see this was asked on cafe a couple of years ago (https://mail.haskell.org/pipermail/haskell-cafe/2013-August/109764.html) but I don't see anything in the source base, so I suppose the situation hasn't changed.
I suggest that I go ahead and try to implement it, since I've done it before (https://github.com/JPMoresmau/BuildWrapper/blob/master/src/Language/Haskell/BuildWrapper/Src.hs#L218). The code needs to be cleaned up, made clearer, etc.
I suppose that at the start it could be made available as a standalone function. I suppose the easiest would be to change the annotation on the AST from SrcSpan to (SrcSpan,Comment).

Any remarks/requirements before I start working on it? Thanks!

### PR DESCRIPTION
**Pull request by JPMoresmau**
Hello, this is a replacement for https://github.com/haskell-suite/haskell-src-exts/pull/225 with hopefully better commit history. Thanks!

### CODE REVIEW

**Comment by pjonsson** [comment]
I apologize for the delay in commenting on your code, I've been too occupied lately. I've looked at this code and beyond a typos and whitespace there is nothing that stands out which is good. Does this code implement all the functionality you had in mind for the feature or do you need some other functionality as well?

There's a typo in the haddock for `associateHaddock`, "relevan" should be "relevant".

There's a missing space to the right of the equals sign in the let-expression in `associateHaddock`. 

Since this is a freestanding module that isn't called from within HSE, can you please add a really basic (typechecking) 3-10 line example of how to use the functionality in the haddock comments? Something along these lines:
```Haskell
goodFunName1 .. = associateHaddock ast
   where ast = parseWithComments file
              .... = ...

goodFunName2 ... = .
```
As you can see I don't know the intended usage but you already have client code for this so the example should be straightforward to make for you.

Comment handling is a "recent" feature in HSE as far as I understand it. Since it wasn't built with that in mind the support is not perfect and I don't think the exactprinter prints comments despite its name. That is unlikely to be a small fix though and it wouldn't be fair to force you to do an overhaul of the exactprinter for getting this feature that you have tested and used elsewhere merged into HSE.

**Comment by JPMoresmau** [comment]
No problem, I'll get the docs and other fixes up asap.

**Comment by JPMoresmau** [comment]
I've done the changes + exposed the module so we can see the haddocks.

**Comment by pjonsson** [comment]
Great! Could you please squash these updates into the earlier commits so that the organization of one commit for each one of <feature, test harness, tests> is preserved into master when I hit the merge button?

**Comment by JPMoresmau** [comment]
I think I managed to squash things correctly. Pfiu

**Comment by pjonsson** [comment]
Great, thank you for the patch!

**Pull request merged**
