### PR TITLE
Add support for GHC 7.8 Pattern Synonyms

### PR DESCRIPTION
**Pull request by mpickering**
This is my first time editing the code base so please let me know if there is anything I have implemented incorrectly.

### CODE REVIEW

**Comment by mpickering** [comment]
I nearly have a new version of this which adds full support.

**Comment by mpickering** [comment]
I think this patch is ready to merge. Please can you review it.

**Comment by pjonsson** [comment]
At the big picture level I have two concerns. The first concern is that `PatternSynonyms3.hs` doesn't pass the tests--`PatternSynonyms3.hs.exactprinter.golden` and `PatternSynonyms3.hs.prettyparser.golden` should just contain `Match`.

My other concern might be related to the first concern; it's generally about the source locations we store in InternalParser.ly and whether they're enough for exact printing. The right amount of source locations with reasonable information needs to be there from day 1 because the code is fragile. I and everybody else always break things somewhere in unforeseen places when we alter the number of source locations. Shrinking source spans later on to improve precision of error messages isn't as fragile in comparison. One example is `pstype` which seems to drop the location of `forall` and `.`  and another is the source annotation on `'pattern' qcon` which is different from `'module' modid` on the line above it.

Can the single use of `where_decls` be replaced with `'where' decllist`?

The placement of semicolons in `pattern_synonym_sig` and similar definitions is on the wrong line compared to the style in the file.

What is "Outsides" in the error message at ExactPrint.hs:735?


Beyond that there's just a bunch of stylistic minor issues. Here's the ones I spotted:

Push the `let sep = ..` into the do at ExactPrint:746 to match the style of the surrounding alternatives.

Inline your definitions of `loc`and `pts`since they're only used once and doesn't make the line too wide.

Can the cases at ExactPrint:746 and :758 be merged into a single one if you move `exactPC rhs` to :766?

There's some extra newlines in ExactPrint.hs:730, ExactPrint.hs:736, Extension.hs:512, ParseUtils.hs:395, InternalParser.ly:1945.

Please align the arrows around ExactPrint.hs:747, Simplify.hs:130, ParseUtils.hs:863, and Pretty:512.

There's no point in being too rigid about line width if it makes the code unreadable. But format Simplify.hs:99 similar to `PatBind` a few lines below since that at least makes the line a bit less too long.

The arrow in Syntax.hs:1194 looks like it's too far too the right.

The previous one kind of fit but the case at Pretty.hs:316 and :342 doesn't fit any longer if my browser line width matches an editor. Break the alternatives into separate lines.

**Comment by mpickering** [comment]
The ExactPrinter test fails because of an extra newline appended to the bottom of the file. I have no idea why it is there and it seems unrelated to this patch.

**Comment by pjonsson** [comment]
Oh. Does the test pass if you remove the extra newline from the end of PatternSynonyms3.hs so that it ends like PatternSynonyms2.hs does?

**Comment by mpickering** [comment]
No it adds an extra newline on the end.

Also there are two things about the ExactPrinter which I am unsure about.

1. What is the intended usage of it? 
2. If an AST element is located then there's no point storing the location of the first keyword as it is necessarily at the same position. There are places in the ExactPrinter which rely on this in a strange way by first checking whether there is a source position in the points list, ignoring it and just printing the string based on the previous observation I mentioned. I mainly elected not to include the position at all rather than do this funny dance but I guess you'd prefer if these positions were also included...

**Comment by pjonsson** [comment]
It still adds a newline at the end even if you remove the extra newline at the end of the input? (With emacs you can get something funky at the end of the file somehow. ESC-G-dd should remove the line the right way in vi.)

The ExactPrinter should be able to roundtrip a file with preserved formatting. I'm not sure what the intended usage for it is but it makes sense to avoid reformatting code to a new style at will.

I agree that the invariant you state is true. I'm suspicious about the correctness of many of these usages you describe since I don't think there are any guarantees in general that the cursor is located at the right position when we start printing the node we're currently pattern matching. There are cases where we do have guarantees about the cursor position since the control flow of the code guarantees that the previous print was something in the parent node and if that print was at the right position the cursor will be located where we want it to be. The code for printing `Symbol` follows the pattern you describe and I don't think it's correct, we just happen to be lucky with our cursor being in the right place in the tests we have.

Will something break if you for example change the pattern matches in `PatSyn` and `PatSynSig` to match on all info points and replace `printString "pattern"` with `printStringAt (pos a) "pattern"`?

Given how fragile the code with the source info points is when changing it I'd prefer to have consistent lunacy rather than a bit of sanity and a bit of lunacy.

**Comment by mpickering** [comment]
I have updated the diff based on your comments. I don't intend to rebase these formatting changes.

**Comment by pjonsson** [comment]
I think you inlined the `pts` in `PatBind` rather than the one you intended to inline in `PatSynSig`.

The semicolons are still at the beginning of the line rather than the end of the previous line in `pattern_synonym_sig` and `pstype`.

Was there a reason to not replace `'pattern' pattern_synonym_lhs '<-' pat where_decls` with `'pattern' pattern_synonym_lhs '<-' pat 'where' decllist` and scrap `where_decls` (or change the definition of `where_decls` to `'where' decllist`)?

**Comment by mpickering** [comment]
I kept it the same to more closely match GHC's parser so that maintenance is easier in the future.

**Comment by mpickering** [comment]
Just rebased onto master

**Comment by pjonsson** [comment]
Here's the part of your file that causes the failure for the prettyprinter and causing the problems with roundtripping for prettyparser:
```Haskell
{-# LANGUAGE PatternSynonyms, DataKinds, ViewPatterns #-}

pattern Single :: () => (Show a) => a -> [a]
```
There's logic in `ppContext` to omit parentheses when the context is either empty or consists of a single assertion.

We don't want to change the context representation for the un-annotated AST. Long term we should get rid of the un-annotated AST but that's a major effort.

**Comment by mpickering** [comment]
Thank you for tracking this down Peter.

It is valid syntax to include just one or neither context in a signature fwiw.

**Comment by pjonsson** [comment]
What is the idiomatic way to write the signature in question? What would HLint suggest if there was support for pattern signatures? We should have that test in our test suite and the test should pass. This is the way we deal with contexts for typeclasses and the reason that ppContext has logic to omit parentheses when you prettyprint `Show a => ..`. That choice means (or meant, I can't remember) `(Show a) => ..` will not (would not) roundtrip since we are missing a set of parentheses in our AST.

**Comment by mpickering** [comment]
I don't know, I've never seen any code which uses pattern synonym signatures.

**Comment by pjonsson** [comment]
I think the current behaviour is incorrect. Here's the example from the GHC manual:
```Haskell
pattern P :: CProv => CReq => t1 -> t2 -> ... -> tN -> t
```
The manual also states "In the common case where CReq is empty, (), it can be omitted altogether.". There is no similar remark that `CProv` is optional which makes sense since the compiler can't know if you omitted `CProv` or `CReq` if it sees `Show a => ..`. That means we can't omit `() =>` in our prettyprinter and thus `ppContext` can't be used for `c1` but it behaves the right way for `c2`.

**Pull request merged**
