### PR TITLE
Add support for type wildcards and expression holes

### LINKED ISSUE #118: Support TypeHoles
```
λ> Language.Haskell.Exts.Annotated.parseExp "_"
ParseFailed (SrcLoc {srcFilename = "<unknown>.hs", srcLine = 1, srcColumn = 2}) "Parse error in expression: _"
```

### PR DESCRIPTION
**Pull request by mpickering**
This patch adds two things.

1. Simple expression holes. GHC accepts both simple and named holes but named holes are also valid variable names so it is not until after parsing that they are treated as holes (if such a variable is not in scope). We only parse `_` to an `ExprHole`.

2. Support for PartialTypeSignatures and NamedWildCards. On the other hand, there is an extension which styles valid identifiers for type wildcards. The rules are a bit tricky about where type wildcards are allowed but I think this covers most of them.

Fixes #118

### CODE REVIEW

**Comment by pjonsson** [comment]
The exact printing of expression holes ignores the location information. Doesn't that mean the exact printing breaks if we add a few spaces before the hole?

Same thing with bundling here, please make a separate commit/pull request for the other two features.

**Comment by mpickering** [comment]
Which two features are you talking about?

**Comment by pjonsson** [comment]
The commit messages mention expression holes, partial type signatures and named wild cards. They might not make sense by themselves but it's nice to have small distinct "features" even if it's partial support for a larger feature. That way the patches are small and Travis ensures that things build cleanly between each one of them.

**Comment by mpickering** [comment]
PartialSignatures and NamedWildCards are the same feature, PartialTypeSignatures doesn't change the parsing at all.

Adding support separately for type wildcards and then NamedWildCards would involved two sets of changes to the exact same set of functions and a bunch of boiler plate between the two patches. I don't see a sensible way to split this patch further.

**Comment by pjonsson** [comment]
A few comments about `checkTyVar`:

Remove the extra parentheses around `ann n`

`startsWithUnderscore` is a descriptive name but I don't think the name matches the implementation. 

Add a comment that explains why the source information is patched. 

I find the logic taxing and I had to think when reading the code. The behaviour of `checkTyVar` differs when `NamedWildCards` is enabled and the variable name starts with an underscore. Does this modulo formatting work?
```Haskell
case n of
   Ident il n' | "_" `isPrefixOf` n && NamedWildCards `elem` exts  -> return $ doStuff n
   _ -> return n
```

You can use `maybePP` instead of defining `prettyWildCard`.

**Comment by mpickering** [comment]
Do you think that in a `TyWildCard` the `Name` should include the underscore or not for named wildcards?

**Comment by pjonsson** [comment]
It makes sense to have the name without the underscore like you have them right now.

**Comment by mpickering** [comment]
Should it be

`TyWildCard (Maybe String)` or `TyWildCard (Maybe Name)`?

It is currently the latter but looking back now this feels a bit strange.

**Comment by mpickering** [comment]
I guess it's like that already for `TyVar` though.

**Comment by mpickering** [comment]
Ok, I refactored `checkTyVar` so it is hopefully clearer and made the suggested changes to `Pretty`.

**Comment by pjonsson** [comment]
Looks good! Can you squash the refactors into the commit they belong in (or submit a new pull request if that is easier for you)?

**Comment by mpickering** [comment]
How do you want me to submit a new pull request? They are already in separate commits and rebasing would involve splitting at least one of them needlessly across three different patches.

**Comment by mpickering** [comment]
Oh it was much easier than I thought so I just rebased it.

**Comment by pjonsson** [comment]
Sorry for not spotting this the first time around. `exactPWildCard` can be replaced by calling `maybeEP exactPC`. Since you're updating the same commit, could you also please remove the extra newline that inserts at Pretty.hs:1910.

**Comment by mpickering** [comment]
Done

**Comment by pjonsson** [comment]
Beautiful small patch, thanks!

**Pull request merged**
