### PR TITLE
MultiParamTypeClasses is needed at definition sites (i.e. class/instance decl)

### PR DESCRIPTION
**Pull request by mvoidex**
rather than on usage sites

For example, this code doesn't require MultiParamTypeClasses:

    foo :: MonadError e m => e -> m ()
    foo = undefined

But this does:

    class Foo a b where

### CODE REVIEW

**Comment by mvoidex** [comment]
Squashed, with new commit message #333

**Comment by mpickering** [comment]
Next time, it is better to rebase and then force push to the same branch so it updates the old pull request.

**Comment by mvoidex** [comment]
@mpickering, ok, thanks, never used rebase+force-push

**Comment by mpickering** [comment]
I merged this now. Thanks!

**Comment by mvoidex** [comment]
Great, thanks!

**Pull request closed without merging**
