### PR TITLE
Make lexWhile account for newlines.

### LINKED ISSUE #218: Line numbers are wrong after multiline GHC_OPTIONS
Given:

    {-# OPTIONS_GHC
        -a
        -a
        -a
        -a
        -a
        -a
        -a
        -a
        -a
        -a
        -a #-}
    main :: IO ()
    main = data

This raises a parse error about `data` on line 3 - seemingly any newlines inside GHC_OPTIONS don't count for additional lines. From https://github.com/ndmitchell/hlint/issues/126

### PR DESCRIPTION
**Pull request by mpickering**
lexWhile ignored newline characters which meant the lexer produced
incorrect line numbers.

Closes #218

### CODE REVIEW

**Comment by pjonsson** [comment]
Does this change not need to update a single one of the existing golden files? The prettyprinter and the exact printer doesn't seem too happy with the change though--`tests/examples/MultiLinePragma.hs.exactprinter.golden` looks really weird. The file should just say "Match".

**Comment by mpickering** [comment]
I see the problem.

**Comment by pjonsson** [comment]
Another style issue is the indentation of `let .. in`when they are on different lines. If `let` is in column 3 then the `in` comes at column 4 in HSE. I don't know why this style was chosen but it's used everywhere so let's not change that style now.

**Comment by mpickering** [comment]
This isn't quite yet right either.

**Comment by mpickering** [comment]
This is nearly right now.. is there a combinator in the pretty printer library which adds a space if there isn't one already but doesn't in there is. 

For example, it would behave like this.

```
"a" <> "b" 
"a " <> "b"
"a" <> " b"
== "a b"
```

**Comment by pjonsson** [comment]
The `drop 1` you removed is to avoid storing ` -fglasgow-exts` as our options pragma since the leading space doesn't serve any purpose. That confuses the lexer if the leading space happens to be a newline though. Can't we just drop leading whitespace that isn't a newline to keep the sane behaviour we currently have and get proper newline behaviour for free?

**Comment by mpickering** [comment]
I'm not sure if this will introduce trailing whitespace somewhere? Currently in the exact printer a leading space is added to the start of the string to account for the `drop 1`, I guess there can be a check to add a space if the first character is not a newline.

**Comment by pjonsson** [comment]
Prettyprinting is good to have but it's not the end of the world-crucial if we insert some extra whitespace somewhere. Our test suite is fairly good so if things don't break there we've tried our best.

A code style thing is that HSE uses explicit cases for pattern matching instead of multiple lines of function declaration. When you're updating addSpace in ExactPrint, please add a one line comment about the lexer dropping initial spaces but not newline so one has an idea why the special case code is there. This isn't the most beautiful solution but that's ok, options pragmas are handled a bit yuckily and we only have one of that kind in the codebase.

The PrettyParser test should contain `Match` but it currently fails. I think it fails because the Prettyprinter inserts too many newlines.

**Comment by mpickering** [comment]
Where is the HSE style explained? I have never seen any other haskell code base which indents the `in` in let expressions one further than the `let` for example and this hard rule about pattern matching seems very strange. I don't want to continue writing patches which trip up on some unwritten style guide. It is not mentioned in the [CONTRIBUTING.md](https://github.com/haskell-suite/haskell-src-exts/blob/master/CONTRIBUTING.md).

**Comment by mpickering** [comment]
I updated the diff to also check for a newline when pretty printing and behave differently if one is there. This makes all the tests pass.

**Comment by pjonsson** [comment]
Great, thank you!

Regarding style: the style isn't consistent throughout HSE and there are a lot of oddities that doesn't follow how other projects look. The oddities are mainly odd though, I don't think we have any style-thing that is outright malign. The rationale for pattern matching through cases is explained somewhere on Roman's blog iirc.

My current stance is that the churn of converting into a different style costs more than the benefits it provides so the second best thing is to try to preserve the style in the surrounding code of where one is working, no matter how odd that style is. I've seen a fair amount of lines in `git blame` dating back to the initial import into Git and that is an advantage since we have a fair idea if something is a regression or has been there for a long time. We're conservative in more areas as well, HSE is not a project that belongs on the bleeding edge when it comes to using new and untried Haskell/GHC extensions. The extra code that we get from not using some extensions is well worth the cost of a few extra lines here and there.

**Pull request merged**
