### PR TITLE
Fix lexing of idents with multiple trailing '#'

### PR DESCRIPTION
**Pull request by erikd**
Tests added.

Closes: https://github.com/haskell-suite/haskell-src-exts/issues/300

### CODE REVIEW

**Comment by mpickering** [comment]
Thanks Erik! I have another branch where I have made some quite significant changes to HSE but this doesn't look like it will cause any conflicts so I just merge it here.

**Comment by erikd** [comment]
Thanks. This fix was really tiny so not likely to cause any problem.

Is your working branch public?

**Comment by mpickering** [comment]
Yep - it is https://github.com/mpickering/haskell-src-exts/tree/one-ast

I got rid of the simplified AST and have added support for most GHC 8.0 features.

**Comment by erikd** [comment]
How close is that to being ready for release? I was thinking of trying to fix a couple of the existing issues but will hold off if merging would be too difficult.

**Comment by mpickering** [comment]
Close, I need to ascertain whether `TypeInType` has actually caused any syntax changes. I think there will also be other problems which I haven't picked up on but it will be hard to find everything before release.

**Comment by erikd** [comment]
@mpickering Has this been merged yet? Anything I can do to help?

**Comment by mpickering** [comment]
There have been multiple releases since this was merged so I think it is fixed?

**Comment by erikd** [comment]
Thanks @mpickering .That means that what I'm currently seeing in hlint is different issue.

**Pull request merged**
