### PR TITLE
Properly pretty print constructor and class operators

### LINKED ISSUE #203: Pretty printing infix class constraints is wrong
Given:

    import Language.Haskell.Exts
    main = putStrLn $ prettyPrint $ fromParseResult $ parseDeclWithMode
        defaultParseMode{extensions=map EnableExtension [minBound..maxBound]}
        "ins :: (:=>) b h => b :- h"

I get:

    ins :: :=> b h => b :- h

I would expect the same input I got in. In particular, note the prefix operator has lost its brackets.

### PR DESCRIPTION
**Pull request by phischu**
Fixes #203
There is an issue with pretty printing that this pull request does not fix:
Deriving class operators:

    data A = A deriving ((:=>))

yields

    data A = A deriving :=>

There is an issue with exact printing that this pull request does not fix, see the file `ConstructorAndClassOperators.hs.exactprinter.golden`.

### CODE REVIEW

**Comment by ndmitchell** [comment]
Thanks for fixing my issue @phischu! Ping @niklasbroberg @feuerbach @pjonsson, this looks like quite a good patch at first glance, so it would be good to merge it or give more feedback so it can be improved.

**Comment by pjonsson** [comment]
Sorry about my absence. I'm unconscious-level swamped at work this upcoming week and the week after that. Will work on my backlog after that.

**Comment by ndmitchell** [comment]
Thanks @pjonsson, sorry to hear about unconscious levels of stuff, but good to hear there is an end in sight.

**Comment by mpickering** [comment]
lgtm :+1:

**Pull request merged**
