### PR TITLE
Typed TH splices and quotations support

### LINKED ISSUE #278: Support typed splices
From https://github.com/ndmitchell/hlint/issues/186 by @MHova.

https://ghc.haskell.org/trac/ghc/wiki/TemplateHaskell/Typed

Hlint currently complains with a Warning: Parse error: $$ when it encounters $$. Almost certainly an HSE issue.

### PR DESCRIPTION
**Pull request by dzhus**
So I got annoyed by https://github.com/ndmitchell/hlint/issues/332 and took a stab at this too. This builds upon #410, using new constructors to parse `$$(`s and `[||`s. I added some minimal tests too. This fixes #278.

### CODE REVIEW

**Comment by dzhus** [comment]
I don't think that test failure has anything to do with this change

**Comment by AshleyYakeley** [comment]
The current version parses `$e` and `$(e)`.

Can you check that this PR parses both `$$e` and `$$(e)`? I believe is does not parse `$$e`.

**Comment by dzhus** [comment]
@AshleyYakeley you're right – it can now do `$$id` as well, tests are update too

**Comment by dzhus** [comment]
CI failure is the same as before – not related to this change I think

**Comment by pwm** [comment]
Hi @dzhus what's the status on this? Any reason it has not been merged yet?

**Comment by dzhus** [comment]
@pwm Probably because maintainer haven't got to do so yet. In the meantime hlint switched to GHC parser and the original problem no longer exists really :)

**Comment by pwm** [comment]
@dzhus Ah thanks, interesting. I'm pretty sure I've built hlint fairly recently from source and ran into this. Maybe they've switched to GHC parser after? Thanks anyway, will investigate.

**Comment by dzhus** [comment]
@pwm actually, I may be wrong – I may have been testing it incorrectly

**Pull request merged**
