### PR TITLE
Comments linking (Fixes #213)

### LINKED ISSUE #213: Support Haddock comments and linking them back to whatever they apply to
Hello, I would like to have the possibility for haskell-src-exts to link Haddock comments to the construct they apply to. I see this was asked on cafe a couple of years ago (https://mail.haskell.org/pipermail/haskell-cafe/2013-August/109764.html) but I don't see anything in the source base, so I suppose the situation hasn't changed.
I suggest that I go ahead and try to implement it, since I've done it before (https://github.com/JPMoresmau/BuildWrapper/blob/master/src/Language/Haskell/BuildWrapper/Src.hs#L218). The code needs to be cleaned up, made clearer, etc.
I suppose that at the start it could be made available as a standalone function. I suppose the easiest would be to change the annotation on the AST from SrcSpan to (SrcSpan,Comment).

Any remarks/requirements before I start working on it? Thanks!

### PR DESCRIPTION
**Pull request by JPMoresmau**
This provides a function to associate elements from the AST to their comments.

### CODE REVIEW

**Comment by pjonsson** [comment]
Thanks for the patch!

The first commit shows that the exact printer doesn't work for that file for some reason (the golden file would contain `Match` if things worked properly).

The second commit touches .gitignore and some other lines not concerning this patch in haskell-src-exts.cabal. That commit also changes the test cases.

Could you organize this as one commit that adds the new functionality you adding, one commit that adds the new test infrastructure, and one commit that adds the test case without touching lines that don't concern the functionality you're adding.

Concerning the code, why does `HaddockComment` contain non-haddock comments in the form of `None`?

Can you describe the intended usage of this feature?

**Comment by JPMoresmau** [comment]
Is the exact printer not printing the comments? Since the whole purpose of the feature is to test comments, what's the way round it?
I can certainly reorganize the commits, but I would appreciated instructions before I wrote the code (when I created the issue and suggested I could implement it) and not three months after writing the code. Some things must have been impacted by my editor (EclipseFP) at the time so I'll clean them up.
Not all comments are Haddock comments, so we try to organize as many comments as we can, hence the None to indicate that case.
The purpose of the feature is simple: to associate comments with explicit nodes of the AST instead of having a big list of comments that may or may not be related to something in the AST. This could be useful to write IDE like tools and is indeed why I wrote the code (in my own library) in the first place.

**Comment by JPMoresmau** [comment]
I've sent pull request https://github.com/haskell-suite/haskell-src-exts/pull/257 with reordered commits.

**Comment by pjonsson** [comment]
I just merged #257 so closing this ticket.

**Pull request closed without merging**
