### PR TITLE
Parse - in type signatures

### LINKED ISSUE #206: Parse fails: subtraction of lifted naturals
I get parser fails when using subtraction on lifted naturals in a type signature; I'm using the current (as of time of posting) master branch from github.

Some examples:

    import Language.Haskell.Exts
    exts = map EnableExtension [DataKinds, KindSignatures, TypeOperators, GADTs]

    -- Test cases
    decls = ["data Vec (n :: Nat) where { VCons :: (m ~ (n-1)) => Double -> Vec m -> Vec n }"
            ,"data Vec (n :: Nat) where { VCons :: ((n-1) ~ m) => Double -> Vec m -> Vec n }"
            ,"data Vec (n :: Nat) where { VCons :: ((m+1) ~ n) => Double -> Vec m -> Vec n }"
            ,"data Vec (n :: Nat) where { VCons :: (n ~ (m+1)) => Double -> Vec m -> Vec n }"
            ]

    main = mapM_ print $ map (parseDeclWithMode m) decls
      where
        m = defaultParseMode {extensions=exts}

The first two fail; the next two parse.

    ParseFailed (SrcLoc "<unknown>.hs" 1 45) "Parse error: -"
    ParseFailed (SrcLoc "<unknown>.hs" 1 41) "Parse error: -"
    ParseOk (GDataDecl (SrcLoc "<unknown>.hs" 1 1) DataType [] (Ident "Vec") [KindedVar (Ident "n") (KindVar (UnQual (Ident "Nat")))] Nothing [GadtDecl (SrcLoc "<unknown>.hs" 1 29) (Ident "VCons") [] (TyForall Nothing [ParenA (EqualP (TyParen (TyInfix (TyVar (Ident "m")) (UnQual (Symbol "+")) (TyPromoted (PromotedInteger 1)))) (TyVar (Ident "n")))] (TyFun (TyCon (UnQual (Ident "Double"))) (TyFun (TyApp (TyCon (UnQual (Ident "Vec"))) (TyVar (Ident "m"))) (TyApp (TyCon (UnQual (Ident "Vec"))) (TyVar (Ident "n"))))))] [])
    ParseOk (GDataDecl (SrcLoc "<unknown>.hs" 1 1) DataType [] (Ident "Vec") [KindedVar (Ident "n") (KindVar (UnQual (Ident "Nat")))] Nothing [GadtDecl (SrcLoc "<unknown>.hs" 1 29) (Ident "VCons") [] (TyForall Nothing [ParenA (EqualP (TyVar (Ident "n")) (TyParen (TyInfix (TyVar (Ident "m")) (UnQual (Symbol "+")) (TyPromoted (PromotedInteger 1)))))] (TyFun (TyCon (UnQual (Ident "Double"))) (TyFun (TyApp (TyCon (UnQual (Ident "Vec"))) (TyVar (Ident "m"))) (TyApp (TyCon (UnQual (Ident "Vec"))) (TyVar (Ident "n"))))))] [])

### PR DESCRIPTION
**Pull request by mpickering**
Fixes #206

### CODE REVIEW

**Comment by pjonsson** [comment]
Shouldn't this check whether some extension is enabled?

**Comment by mpickering** [comment]
The GHC parser accepts the test file without any additional extensions turned on.

**Comment by pjonsson** [comment]
Should that really parse without any extensions enabled?

Looking at older GHCs--If I keep the first definition of `Vec` and add a definition of `Nat` to the test case this is what I get with ghci 7.8.3:
```
[1 of 1] Compiling Foo              ( Foo.hs, interpreted )

Foo.hs:7:45: Not in scope: type constructor or class ‘-’
```

**Comment by mpickering** [comment]
I think the check happens in the renamer. On 7.10, the parser parses he file fine and I get the following error which comes from [here](https://github.com/ghc/ghc/blob/4cd008b6c1751c5533ab7eac32d17c9749e4758e/compiler/rename/RnTypes.hs#L1052)

```
test2.hs:4:26:
    Illegal operator ‘-’ in type ‘n - 1’
      Use TypeOperators to allow operators in types
```

**Comment by pjonsson** [comment]
So the GHC API allows you to parse files without the proper extensions enabled, but if you try to do more stages of the compiler pipeline you get an unconditional failure because `TypeOperators` isn't enabled?

**Comment by mpickering** [comment]
It checks for some extensions (`PatternSynonyms`) in the parser (usually ones which steal syntax) but for others only at later stages in the pipeline. In this case what you say is right.

**Comment by pjonsson** [comment]
I don't think we should admit programs that are beyond whatever the latest Haskell standard specifies without the proper extension enabled since that is mostly the behaviour of HSE right now. GHC has been changed in the past after people started asking questions why programs without extensions enabled actually parsed with GHC.

If there are cases where we don't follow that guideline it's either because we don't know about it (so a bug), it's not feasible to implement a proper check (still a bug), or a swath of programs would break if we actually enforced the guideline (well.. bug, but cost/benefit ratio of the current behaviour overrides the concern about the bug). In this case it seems eminently feasible to implement a check since the programs it affects are using advanced experimental stuff in GHC anyways.

**Comment by mpickering** [comment]
I just tried and there is already a check for whether `TypeOperators` is enabled which works for this as well and is in `parseUtils`.

**Pull request merged**
