### PR TITLE
KindSignatures revamp

### LINKED ISSUE #202: Pretty printing kind signatures is wrong
Given:

    import Language.Haskell.Exts
    main = putStrLn $ prettyPrint $ fromParseResult $ parseDeclWithMode
        defaultParseMode{extensions=map EnableExtension [minBound..maxBound]}
        "type SEither (z_aizC :: Either a_a7md b_a7me) = Sing z_aizC"

I get:

    type SEither (z_aizC :: Either (a_a7md b_a7me)) = Sing z_aizC

I would expect the same input I got in. In particular, note the invalid (semantics changing) brackets around the `Either` arguments.

### PR DESCRIPTION
**Pull request by mpickering**
This patch contains three changes

1. KindApp is parsed as left associative (Fixes #202)
2. Removed KindBang as it just isn't a kind.
3. Modified KindList so it can only contain a single kind.
   (It is the kind of promoted lists, not a promoted list)

Also updated the test.

### CODE REVIEW

**Comment by pjonsson** [comment]
I appreciate your effort but you're bundling too much functionality in a single commit and/or pull request.

Could you please submit a new pull request that just fixes 1) because I'm 100% confident we want that.

It sounds like 3) is something we want in a separate pull request as well. Is the issue that we currently parse more programs than GHC or is it just an overly lenient AST type in HSE?

2) I'm a bit more hesitant over since I've completely flushed my cache from HSE code lately. Ignoring principles--how can KindBang be removed without hurting the parsing or prettyprinting functionality?

**Comment by mpickering** [comment]
I have split the commit into 4 separate commits for you to review individually. 

3) HSE parses more programs that GHC.
2) This is again a case where HSE accepts more programs that GHC. There is no such kind as `!`.

**Comment by pjonsson** [comment]
@niklasbroberg: `KindBang` dates back to the giant commit with exact printing in August in 2009. Any recollection of why you did that 6 years ago?

**Comment by pjonsson** [comment]
Note to myself: besides the existence of the mysterious KindBang, the other commits look good.

**Pull request merged**
