### PR TITLE
Improve out of the parser tests

### PR DESCRIPTION
**Pull request by mpickering**
I don't think the current tests are very useful as if they fail it is very difficult to see where they have failed.

### CODE REVIEW

**Comment by pjonsson** [comment]
I agree about the difficulty in detecting failures and this looks like a good thing. I'm worried that we are leaving things out of the test outputs if we prettify them though--does the pretty printing you added preserve all the information we have in our current format?

**Comment by mpickering** [comment]
I just used the `ppShow` function from `pretty-show`. I don't know that it doesn't throw away information but I think it's a far assumption that it doesn't?

**Comment by pjonsson** [comment]
Sounds reasonable. Let's merge this after either #270 or #272 is merged.

**Comment by mpickering** [comment]
Updated the tests now for the latest merge.

**Pull request merged**
